### ISSUE TITLE
Suggestion: Pure CSS Dropdown

### ISSUE THREAD

**Issue by roemhildtg** [picturepan2/spectre#126]
What do you think about adding a pure-css dropdown component? This component example is toggled using the :focus selector. 

css
```css
.dropdown-menu {
    display: none;
    position: absolute;
}
a.dropdown-toggle:focus,
a.dropdown-toggle:active {
    background: #f2f2f2;
}
a.dropdown-toggle:focus+.dropdown-menu,
a.dropdown-toggle:active+.dropdown-menu {
    display: block;
}
.dropdown-menu:hover {
    display: block;
}
```

example:
```html
    <div class="dropdown float-left">
        <a href="#" onclick="javascript:return false;" class="btn btn-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true">Dropdown Menu
          <i class="caret fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu menu">
                <li class="menu-item">
                    <a href="#">
                        <i class="fa fa-fw fa-map-marker"></i> Dropdown Item 1</a>
                </li>
                <li class="menu-item">
                    <a href="#">
                        <i class="fa fa-fw fa-map-marker"></i> Dropdown Item 2</a>
                </li>
                <li class="menu-item">
                    <a href="#">
                        <i class="fa fa-fw fa-map-marker"></i> Dropdown Item 3</a>
                </li>
        </ul>
    </div>
```

It looks something like this:
![image](https://cloud.githubusercontent.com/assets/5471079/20976681/e42cae88-bc68-11e6-94ac-9092565ea8c0.png)
