### ISSUE TITLE
<small> not taking effect (font size)

### ISSUE THREAD

**Issue by ThunderRoid** [picturepan2/spectre#131]
![image](https://cloud.githubusercontent.com/assets/3328263/21638175/0e9ee53e-d21f-11e6-8847-5d7a95bc3c8e.png)

Please change to
```css
small {
    font-size: 80% !important;
}
```
