### ISSUE TITLE
Dropdown with float-right appears off screen

### ISSUE THREAD

**Issue by roemhildtg** [picturepan2/spectre#137]
I've found a potential issue with the new dropdown, if you have a navbar, with a dropdown element floated right with class `float-right` the menu element appears off the screen. 

A simple fix is to have a `dropdown-right` class which would have the css rule 
```css
.dropdown.dropdown-right .menu {
  right:0;
  left: inherit;
}
```
