### ISSUE TITLE
Shadow color for 'is-danger' inputs

### ISSUE THREAD

**Issue by antimatter96** [picturepan2/spectre#153]
If we apply a `is-danger` class to an input then on focus is leads to a black shadow around a red border
![qa](https://cloud.githubusercontent.com/assets/12068176/23557162/1ece2b72-0055-11e7-8104-333760210c0b.png)

**Comment by antimatter96** [comment]
I propose the following addition
```css
.is-danger:focus{
   box-shadow: 0 0 0 0.2rem rgba(232, 86, 0, .15);
}
```

leading to

![qqqaaa](https://cloud.githubusercontent.com/assets/12068176/23557476/2f21fe08-0056-11e7-9d16-2e4bce5718a9.png)
