### ISSUE TITLE
Suggestion: add classes for text-colors

### ISSUE THREAD

**Issue by Dewep** [picturepan2/spectre#205]
Hi,

First of all, very good framework, thank you for your work!

I was wondering if it could not be useful to add classes for the color property (for primary/success/warning/error)? Something like that:

```less
.text-primary {
  color: @primary-color;
}
.text-secondary {
  color: @secondary-color;
}
.text-success {
  color: @control-color-success;
}
.text-warning {
  color: @control-color-warning;
}
.text-error {
  color: @control-color-error;
}
```

In my case, I wanted to change the color of my icons, and I found no class to do that (except put them in buttons/labels).

What do you think about that? I can make a pull request if it can help.
Thanks.
