### ISSUE TITLE
tooltip能否支持换行呢？

### ISSUE THREAD

**Issue by ydq** [picturepan2/spectre#292]
感谢作者提供了这么棒的一个前端库。

在使用中我遇到一个问题，当使用css的换行`&#10;`时因为现在的spectre中：
```css
.tooltip::after{white-space: nowrap}
```
所以，提示文字不能换行，不排除某些时候提示文字是想换行的，所以建议将这个修改为：
```css
.tooltip::after{white-space: pre}
```
或者说现有的保持不变，然后专门定义一个tooltip-xxx的换行class，来支持tooltip的换行
