### ISSUE TITLE
More colors

### ISSUE THREAD

**Issue by AGhasemzadeh** [picturepan2/spectre#342]
I think it would be good idea to have more colors for buttons,cards.

Example  of bootstrap:
https://getbootstrap.com/docs/4.0/components/buttons/
https://getbootstrap.com/docs/4.0/components/card/#background-and-color

**Comment by picturepan2** [comment]
@AGhasemzadeh What button colors do you need?

**Comment by AGhasemzadeh** [comment]
exactly like boostrap and we can have guide to add more colors.

**Comment by roemhildtg** [comment]
You can add these additional colors quite easily. I did this with toasts:

```less
toast-item {
    .toast.toast-warning {
        background: #fcf8e3;
        border-color: #faebcc;
        color: #8a6d3b;
    }
    .toast.toast-info {
        color: #31708f;
        background-color: #d9edf7;
        border-color: #bce8f1;
    }
}
```
