### ISSUE TITLE
-moz-appearance missing

### ISSUE THREAD

**Issue by Vectrex** [picturepan2/spectre#381]
Whilst the form element examples on https://picturepan2.github.io have the namespaced Mozilla properties set, they are missing in the repository version. A select element on Firefox therefore still shows the stock drop-down arrow.

**Comment by picturepan2** [comment]
@Vectrex Checking.

**Comment by picturepan2** [comment]
@Vectrex I have checked and all are fine. What do you mean by "the repository version"?

**Comment by Vectrex** [comment]
Looking at the select in
https://picturepan2.github.io/spectre/elements.html#forms
the resulting rule according to the web development tools reads

```css
.form-select {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border: .05rem solid #caced7;
    border-radius: .1rem;
    color: inherit;
    font-size: .8rem;
    height: 1.8rem;
    line-height: 1rem;
    outline: none;
    padding: .35rem .4rem;
        padding-right: 0.4rem;
    vertical-align: middle;
    width: 100%;
}
```

I can find this rule set in the dist file, but the scss files which I use to combine Spectre.css with my customizations (just pulled from the repo) don't create a "moz"-prefixed property and searching through all scss files in the src folder for "-appearance" results in
```
Searching 73 files for "-appearance"

src/_normalize.scss:
  281  [type="reset"],
  282  [type="submit"] {
  283:   -webkit-appearance: button; /* 2 */
  284  }
  285  
  ...
  371  
  372  [type="search"] {
  373:   -webkit-appearance: textfield; /* 1 */
  374    outline-offset: -2px; /* 2 */
  375  }
  ...
  381  [type="search"]::-webkit-search-cancel-button,
  382  [type="search"]::-webkit-search-decoration {
  383:   -webkit-appearance: none;
  384  }
  385  
  ...
  390  
  391  ::-webkit-file-upload-button {
  392:   -webkit-appearance: button; /* 1 */
  393    font: inherit; /* 2 */
  394  }

src/_sliders.scss:
   21    // Slider Thumb
   22    &::-webkit-slider-thumb {
   23:     -webkit-appearance: none;
   24      background: $primary-color;
   25      border: 0;

5 matches across 2 files

```
Searching for "-appearance" in the result file yields five matches, all with a "-webkit" prefix and none addressing a select element.
The scss file to build this resulting CSS file:

```scss
$primary-color: #0089CC;
$secondary-color: #FF9400;
$base-font-family: "verbcond";

@import "spectre/spectre";
@import "spectre/spectre-exp";
@import "spectre/spectre-icons";

.nav-item {
  & > span {
    padding: $unit-1 $unit-2;
  }
  &.active > span {
    font-weight: bold;
  }
}
...
```
