### ISSUE TITLE
Autocomplete menu shows up underneath other menu

### ISSUE THREAD

**Issue by roemhildtg** [picturepan2/spectre#498]
http://jsbin.com/ziracuxeda/edit?html,js,output

If I position an auto complete above a menu, the auto complete menu (when visible) shows up underneath the other menu.

**Comment by Tex-tang** [comment]
Do you want the menu auto move to below and not underneath by the auto complete menu?

If that is what you want ,you can simply
```css
.form-autocomplete .menu {
  position: auto;
}
```
