### ISSUE TITLE
Remove outline

### ISSUE THREAD

**Issue by ctuxboy** [picturepan2/spectre#555]
Hello,

How remove 'outline' border from clicked elements?

I try it with this:

> *:focus {outline:none;}

But doesn't disappear.

**Comment by Vectrex** [comment]
It's a `box-shadow`. You can test it with your browsers developer tools.

From _base.scss

```scss
a {
  color: $link-color;
  outline: none;
  text-decoration: none;

  &:focus {
    @include control-shadow();
  }
...
}
```
