### ISSUE TITLE
Form suggestions

### ISSUE THREAD

**Issue by davestewart** [picturepan2/spectre#565]
Hi there,

Great library! I'm loving it. Simple enough that you don't spend ages working things out.

And I love the fact that basic typography is included, and doesn't need extra classes!

A few things missing I'm finding missing in my form development. I'm not sure if these should be provided with the library, or if you think it is outside the library's remit:

### 1. An intro for forms groups

Often in forms, I will want to provide an introductory sentence, or paragraph, to give the user some context of prompt to start entering information.

This could be done with styling that's more than a paragraph, but less than a toast.

### 2. Fieldsets and legends

I didn't see anything documented for this.

What are your suggestions to give forms regions, especially for larger forms?

### 3. Offsets for flexbox

I've added this SCSS, which gives me `.off-n` classes to push things like under-input labels over:

```scss
@for $0 from 1 through 11 {
  .off-#{$i} {
    margin-left: calc(100% / 12 * #{$i});
  }
}
```

I need to look at how to make this responsive.

### 4. An end-of form button group for submission

This is useful because the buttons need to be visually separated.

Currently I'm doing this:

```css
.form-group.button-group {
  margin-top: 1.5rem;
  border-top: 1px solid $gray-color-light;
  padding-top: 1rem;
  text-align: right;
}
```
```html
<div class="form-group button-group">
...
</div>
```

Thanks a lot again for making this simple, yet effective framework.

**Comment by davestewart** [comment]
So for the grid offsets, I took a look at the media query stuff, and came up with:

```scss
// flexbox offsets
[class*="off-"][class~="col-12"] {
  margin-left: 0
}
@for $i from 1 through 11 {
  .off-#{$i} {
    margin-left: calc(100% / 12 * #{$i});
  }
}

@media (max-width: $size-xl) {
  [class*="off-"][class~="col-xl-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-xl-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}
@media (max-width: $size-lg) {
  [class*="off-"][class~="col-lg-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-lg-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}
@media (max-width: $size-md) {
  [class*="off-"][class~="col-md-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-md-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}
@media (max-width: $size-sm) {
  [class*="off-"][class~="col-sm-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-sm-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}
@media (max-width: $size-xs) {
  [class*="off-"][class~="col-xs-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-xs-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}
```

It's 3190 bytes when spat out a CSS. There may be ways to optimise this.

The classes are:

```
.off-(0-11)
.off-xl-(0-11)
.off-lg-(0-11)
.off-md-(0-11)
.off-sm-(0-11)
.off-xs-(0-11) 
```

I tested it at a few different sizes and it seems to work:

```html
<!-- this is the main group -->
<div class="form-group">
  <div class="col-3 col-sm-12 col-md-6">
    <label class="form-label">Name:</label>
  </div>
  <div class="col-9 col-sm-12 col-md-6">
    <input class="form-input" type="text" v-model="folderName" autocomplete="off" placeholder="Workspaces">
  </div>
</div>

<!-- this is the offset group -->
<div class="off-3 off-sm-0 off-md-6">
  <label class="form-info" v-if="type === 'new'">You can move this folder later</label>
</div>
```

What do you think?

**Comment by davestewart** [comment]
I've just seen that the modal footer provides a nice way to do modal forms:

![image](https://user-images.githubusercontent.com/132681/52674206-c0188b80-2f1a-11e9-9d12-7e4ad83d73e7.png)

This is pretty much exactly what is needed for non-modal forms.

In the modal, I just have to have the form wrap content and footer which works great:

![image](https://user-images.githubusercontent.com/132681/52674449-85632300-2f1b-11e9-9a5b-1943694b0858.png)

Perhaps a `.form-footer` and as mentioned in point 1 above, a `.form-header` would work?

**Comment by jonasnordlund** [comment]
As for legends, I recently ran into this -- as in legends not separating their containing subsections when using Spectre. I've added this minor change to my "Spectre fixes" CSS that I apply in my forms after Spectre.css:

```css
fieldset {
    margin-top: 2rem;
}
```

One may want to adjust the exact spacing after own taste. I tried to keep it just enough so that there's a slight gap between the preceding form group. I didn't need to change the `legend` style as it's already bold and looking great.
