### ISSUE TITLE
Grid offsets

### ISSUE THREAD

**Issue by davestewart** [picturepan2/spectre#566]
I was writing in #565 about grid offsets, and proposed a solution there, but I've moved it here so it will be easier for other to find this.

I've taken a stab at grid offsets, and came up with:

```scss
// flexbox offsets
[class*="off-"][class~="col-12"] {
  margin-left: 0
}
@for $i from 1 through 11 {
  .off-#{$i} {
    margin-left: calc(100% / 12 * #{$i});
  }
}

@media (max-width: $size-xl) {
  [class*="off-"][class~="col-xl-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-xl-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}

@media (max-width: $size-lg) {
  [class*="off-"][class~="col-lg-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-lg-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}

@media (max-width: $size-md) {
  [class*="off-"][class~="col-md-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-md-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}

@media (max-width: $size-sm) {
  [class*="off-"][class~="col-sm-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-sm-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}

@media (max-width: $size-xs) {
  [class*="off-"][class~="col-xs-12"] {
    margin-left: 0
  }
  @for $i from 0 through 11 {
    .off-xs-#{$i} {
      margin-left: calc(100% / 12 * #{$i});
    }
  }
}
```

It's 3190 bytes when spat out as CSS.

There may be ways to optimise this, or it could be a separate `offsets.scss` file, so could be imported only when needed, as I am doing with the rest of the library:

```css
// Layout
@import "../../../node_modules/spectre.css/src/layout.scss";
// @import "../../../node_modules/spectre.css/src/hero.scss";
@import "../../../node_modules/spectre.css/src/navbar.scss";
```

The classes are:

```
.off-(0-11)
.off-xl-(0-11)
.off-lg-(0-11)
.off-md-(0-11)
.off-sm-(0-11)
.off-xs-(0-11) 
```

I tested it at a few different sizes and it seems to work:

```html
<!-- this is the main group -->
<div class="form-group">
  <div class="col-3 col-sm-12 col-md-6">
    <label class="form-label">Name:</label>
  </div>
  <div class="col-9 col-sm-12 col-md-6">
    <input class="form-input" type="text" v-model="folderName" autocomplete="off" placeholder="Workspaces">
  </div>
</div>

<!-- this is the offset group -->
<div class="off-3 off-sm-0 off-md-6">
  <label class="form-info" v-if="type === 'new'">You can move this folder later</label>
</div>
```

Note that you can use the `off-*` classes without also using the `col-` classes on the same element.

If there are positive comments on this, I could PR along with a docs update.
