### ISSUE TITLE
Add an option for multiline grid maybe?

### ISSUE THREAD

**Issue by kevbook** [picturepan2/spectre#64]
```css
.columns.multiline {
    flex-wrap: wrap;
}
```

![unspecified](https://cloud.githubusercontent.com/assets/926720/15546022/4c5dcdda-226c-11e6-9325-efc6c4b79ac9.png)
