### ISSUE TITLE
Meters with error

### ISSUE THREAD

**Issue by cafc3** [picturepan2/spectre#682]
Hi,
with the update of browser like chrome to 94 version, and others, the meters doesn't work anymore. is it possible to correct/update them?
thanks

**Comment by laurentpayot** [comment]
@cafc3 you can fix this by adding the following style:
```css
.meter {
    appearance: meter;
}
```
