### ISSUE TITLE
centering columns?

### ISSUE THREAD

**Issue by eddiewang** [picturepan2/spectre#79]
Hi, is there currently a way to offset, or center columns?

**Comment by picturepan2** [comment]
There is no offset classes right now. You could try the class `centered` for centering a column.

**Comment by eddiewang** [comment]
i'm pretty sure the columns are floated right? centered utility class doesn't work for that.

**Comment by kevbook** [comment]
On parent - ie .columns class
```css
.columns {
  align-items: center;
  flex-direction: column;
}
```

or 
```html
<div class="columns">
      <div class="column col-9 centered"> </div>
</div>
```
