### ISSUE TITLE
Need bigger switch/checkbox/radio buttons

### ISSUE THREAD

**Issue by bybrunobarros** [picturepan2/spectre#80]
Hi,

Currently you can change input sizes with .input-sm/.input-lg, but there is no equivalent for switch/checkbox/radio buttons.
These elements should be able to be resized.

Nice job by the way and thanks for the framework.

**Comment by tomlutzenberger** [comment]
Seems legit.
But in case of checkboxes and radio buttons this would mean (correct me if I'm wrong), that they have to be overwritten to

0. even be resizable
0. match the look of the other form-controls

**Comment by bybrunobarros** [comment]
I'd say
```css
.form-checkbox .form-icon.input-lg {
  height: 2.4rem;
  width: 2.4rem;
}
.form-checkbox input:checked + .form-icon.input-lg::after {
  height: 1.4rem;
  left: 46%;
  top: 38%;
  width: .8rem;
}
```
should be enough for the checkbox.

I don't understand the second point, they already have the same look and feel.
